fix endpoint parsing in jupyter.py
Added parsing of the endpoints.yml file when using the chat method of the jupyter.py class. This was causing the error `AttributeError: 'str' object has no attribute 'event_broker'` when creating an agent inside the jupyer.chat method